Add bulk inserting/updating list of students
cppseminar/APC pull request #21
Opened 2022-06-16 09:25 UTC by slavo-furman

This PR contains two commits. 

First is updating the userservice app by adding a new http api for bulk inserting/updating list of students. This new http api is implemented by extending /user/ endpoint and allow call it via http POST where list of student is payload in body of http message. In case of success it returns 201 Created status code (I know it is kind of controversial topic, but I prefer that all http api calls return clear status code). Underlying service method simply use C# Azure SDK for upserting Azure Table Storage.

Second adds web ui (simple bootstrap styled html input form) to /admin/users page of presentation app. User is expected to insert list of email addresses, one email address per line, no explicit separators, along with claim name and claim value which will be applied in same way to each email address. Email addresses are validated before we pass them to underlying service. Email validator is implemented in EmailValidator class. Underlying service method, implemented in AuthenticationService class simply forms json payload from passed list of students and call http api endpoint implemented in userservice app.

2022-06-17 07:59 UTC, koscelansky requested changes

2022-06-20 08:49 UTC, slavo-furman commented on cppseminar/presentation/Model/EmailValidator.cs
> +                return Regex.IsMatch(email,
I agree. Changed.

2022-06-20 08:51 UTC, slavo-furman commented on cppseminar/userservice/Controllers/UserController.cs
> +        public async Task<IActionResult> UpdateListOfStudents([FromBody] List<UserModel> listOfStudents)
All mentions of "students" in identifiers were changed to "users".

2022-06-20 08:51 UTC, slavo-furman commented on cppseminar/userservice/Services/UserDbService.cs
> +                for (int i = 0; i < listOfStudents.Count; i++)
Changed to foreach loop.

2022-06-20 09:02 UTC, slavo-furman commented on cppseminar/presentation/Pages/Shared/_Layout.cshtml
> +    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.4/jquery.validate.min.js" integrity="sha512-FOhq9HThdn7ltbK8abmGn60A/EMtEzIzv1rvuh+DqzJtSGq8BRdEN0U+j0iKEIffiw/yEtVuladk6r
I originally thought that this is needed for form validation to work. But it seems that at least basic validation is working fine without it. Removed.

2022-06-20 12:29 UTC, slavo-furman commented on cppseminar/presentation/Pages/Admin/Users/Index.cshtml.cs
> +        public string studentlist { get; set; }
Model, service and input form for update list of users were completely rewritten as requested, so given question is no longer relevant.

2022-06-20 12:30 UTC, slavo-furman commented on cppseminar/presentation/Pages/Admin/Users/Index.cshtml.cs
> +                if (string.IsNullOrWhiteSpace(Request.Form[entry.Key].ToString()))
Model, service and input form for update list of users were completely rewritten as requested, so given question is no longer relevant.

2022-06-20 12:30 UTC, slavo-furman commented on cppseminar/presentation/Pages/Admin/Users/Index.cshtml
> +    @Html.AntiForgeryToken()
Model, service and input form for update list of users were completely rewritten as requested, so given question is no longer relevant.

2022-06-21 09:44 UTC, lukas-manduch requested changes

2022-06-21 09:44 UTC, lukas-manduch commented on cppseminar/userservice/Controllers/UserController.cs
> +                _logger.LogError($"Problem in [UploadListOfUsers] action: {ex.Message}");
Preco je tu pouzity iny string builder pre logger nez ten standradny? Myslim $ na zaciatku. Bud by som pouzival jeden sposob, alebo druhy

2022-06-21 09:44 UTC, lukas-manduch commented on cppseminar/userservice/Controllers/UserController.cs
> +            catch (Exception ex)
Tento catch podla mna nemoze fungovat, lebo vo funkcii co volas je tiez globalny catch

2022-06-21 09:44 UTC, lukas-manduch commented on cppseminar/presentation/Services/UserService.cs
> +            var stringContent = new StringContent(userListAsJson, Encoding.UTF8, "application/json");
Aky ma zmysel definovat dva krat to "application/json"? Myslim, preco je to aj tu aj o 5 riadkov vyssie

2022-06-21 09:44 UTC, lukas-manduch commented on cppseminar/presentation/Services/AuthenticationService.cs
> +using System.Text;
Neviem ci mi to github zobrazuje spravne, ale toto vyzera ako keby si pridal nejake veci navyse do suboru, s ktorym si nic nerobil

2022-06-21 09:44 UTC, lukas-manduch commented on cppseminar/presentation/Pages/Admin/Users/Create.cshtml.cs
> +    [Authorize(Policy = "Administrator")]
Toto tu urcite nema byt. V ziadnom inom subore to tiez nie je pouzite

2022-06-21 09:44 UTC, lukas-manduch commented on cppseminar/presentation/Model/EmailValidator.cs
> +namespace presentation.Model
Nemyslim si ze validator by mal byt medzi Models . Tam su veci reprezentujuce data a vacsinou bez nejakej aplikacnej logiky. Toto je presny opak

2022-06-21 09:44 UTC, lukas-manduch commented on cppseminar/presentation/Model/EmailValidator.cs
> +            catch (RegexMatchTimeoutException)
Toto je trocha zbytocny catch navyse, nie?

2022-06-21 09:44 UTC, lukas-manduch commented on cppseminar/presentation/Pages/Admin/Users/Index.cshtml
> +        <p><th:a asp-page="/Admin/Users/Create">Update user list</th:a></p>
Trocha mi nie je jasne, preco vsade v texte je to update user list, zatial co v suboroch je to create. Pride mi to ako zbytocna nekonzistencia uz zo zaciatku

2022-06-21 09:51 UTC, koscelansky commented on cppseminar/userservice/Controllers/UserController.cs
> +            catch (Exception ex)
Tak toto nesuhlasim, ze je problem tu, ked tam nema byt v tej funkcii co sa vola.

2022-06-21 13:57 UTC, merged